import type { SubscriptionPlanDefinition, SubscriptionPlanType } from '@/types/subscriptions';

export const SUBSCRIPTION_PLANS: Record<SubscriptionPlanType, SubscriptionPlanDefinition> = {
  daily: {
    type: 'daily',
    name: '1 Day Pass',
    amount: 2000,
    currency: 'UGX',
    durationUnit: 'days',
    durationValue: 1,
    description: 'Premium access for 24 hours.',
  },
  seven_days: {
    type: 'seven_days',
    name: '7 Days Pass',
    amount: 5000,
    currency: 'UGX',
    durationUnit: 'days',
    durationValue: 7,
    description: 'Premium access for 7 straight days.',
  },
  fourteen_days: {
    type: 'fourteen_days',
    name: '14 Days Pass',
    amount: 7000,
    currency: 'UGX',
    durationUnit: 'days',
    durationValue: 14,
    description: 'Premium access for 14 straight days.',
  },
  monthly: {
    type: 'monthly',
    name: '1 Month Pass',
    amount: 15000,
    currency: 'UGX',
    durationUnit: 'months',
    durationValue: 1,
    description: 'Premium access for a full month.',
  },
  two_months: {
    type: 'two_months',
    name: '2 Months Pass',
    amount: 22000,
    currency: 'UGX',
    durationUnit: 'months',
    durationValue: 2,
    description: 'Premium access for 2 full months.',
  },
  three_months: {
    type: 'three_months',
    name: '3 Months Pass',
    amount: 30000,
    currency: 'UGX',
    durationUnit: 'months',
    durationValue: 3,
    description: 'Premium access for 3 full months.',
  },
  six_months: {
    type: 'six_months',
    name: '6 Months Pass',
    amount: 60000,
    currency: 'UGX',
    durationUnit: 'months',
    durationValue: 6,
    description: 'Premium access for 6 full months.',
  },
  twelve_months: {
    type: 'twelve_months',
    name: '12 Months Pass',
    amount: 120000,
    currency: 'UGX',
    durationUnit: 'months',
    durationValue: 12,
    description: 'Premium access for 12 full months.',
  },
};

export const SUBSCRIPTION_PLAN_LIST = Object.values(SUBSCRIPTION_PLANS);
