export const VJ_DIRECTORY = [
  { id: 'vj-aaron', name: 'VJ Aaron', image: '/images/vjs/default.jpg' },
  { id: 'vj-ashim', name: 'VJ Ashim', image: '/images/vjs/default.jpg' },
  { id: 'vj-banks', name: 'VJ Banks', image: '/images/vjs/default.jpg' },
  { id: 'vj-baros', name: 'VJ Baros', image: '/images/vjs/default.jpg' },
  { id: 'vj-bonny', name: 'VJ Bonny', image: '/images/vjs/default.jpg' },
  { id: 'vj-cads', name: 'VJ Cads', image: '/images/vjs/default.jpg' },
  { id: 'vj-dan-de', name: 'VJ Dan De', image: '/images/vjs/default.jpg' },
  { id: 'vj-eddy', name: 'VJ Eddy', image: '/images/vjs/default.jpg' },
  { id: 'vj-emmy', name: 'VJ Emmy', image: '/images/vjs/default.jpg' },
  { id: 'vj-fredy', name: 'VJ Fredy', image: '/images/vjs/default.jpg' },
  { id: 'vj-hd', name: 'VJ HD', image: '/images/vjs/default.jpg' },
  { id: 'vj-heavy-q', name: 'VJ Heavy Q', image: '/images/vjs/default.jpg' },
  { id: 'vj-henrico', name: 'VJ Henrico', image: '/images/vjs/default.jpg' },
  { id: 'vj-ice-p', name: 'VJ Ice P', image: '/images/vjs/default.jpg' },
  { id: 'vj-illess', name: 'VJ Illess', image: '/images/vjs/default.jpg' },
  { id: 'vj-isma-k', name: 'VJ Isma K', image: '/images/vjs/default.jpg' },
  { id: 'vj-ivo', name: 'VJ Ivo', image: '/images/vjs/default.jpg' },
  { id: 'vj-jimmy', name: 'VJ Jimmy', image: '/images/vjs/default.jpg' },
  { id: 'vj-jingo', name: 'VJ Jingo', image: '/images/vjs/default.jpg' },
  { id: 'vj-joe', name: 'VJ Joe', image: '/images/vjs/default.jpg' },
  { id: 'vj-jovan', name: 'VJ Jovan', image: '/images/vjs/default.jpg' },
  { id: 'vj-jumpers', name: 'VJ Jumpers', image: '/images/vjs/default.jpg' },
  { id: 'vj-junior', name: 'VJ Junior', image: '/images/vjs/default.jpg' },
  { id: 'vj-kamran', name: 'VJ Kamran', image: '/images/vjs/default.jpg' },
  { id: 'vj-kevo', name: 'VJ Kevo', image: '/images/vjs/default.jpg' },
  { id: 'vj-kimuli', name: 'VJ Kimuli', image: '/images/vjs/default.jpg' },
  { id: 'vj-kin', name: 'VJ Kin', image: '/images/vjs/default.jpg' },
  { id: 'vj-kriss-sweet', name: 'VJ Kriss Sweet', image: '/images/vjs/default.jpg' },
  { id: 'vj-ks', name: 'VJ KS', image: '/images/vjs/default.jpg' },
  { id: 'vj-lance', name: 'VJ Lance', image: '/images/vjs/default.jpg' },
  { id: 'vj-lash', name: 'VJ Lash', image: '/images/vjs/default.jpg' },
  { id: 'vj-little-t', name: 'VJ Little T', image: '/images/vjs/default.jpg' },
  { id: 'vj-mark', name: 'VJ Mark', image: '/images/vjs/default.jpg' },
  { id: 'vj-martin-k', name: 'VJ Martin K', image: '/images/vjs/default.jpg' },
  { id: 'vj-mk', name: 'VJ MK', image: '/images/vjs/default.jpg' },
  { id: 'vj-mosco', name: 'VJ Mosco', image: '/images/vjs/default.jpg' },
  { id: 'vj-mox', name: 'VJ Mox', image: '/images/vjs/default.jpg' },
  { id: 'vj-muba', name: 'VJ Muba', image: '/images/vjs/default.jpg' },
  { id: 'vj-musa', name: 'VJ Musa', image: '/images/vjs/default.jpg' },
  { id: 'vj-neil', name: 'VJ Neil', image: '/images/vjs/default.jpg' },
  { id: 'vj-pauleta', name: 'VJ Pauleta', image: '/images/vjs/default.jpg' },
  { id: 'vj-pax', name: 'VJ Pax', image: '/images/vjs/default.jpg' },
  { id: 'vj-phoenix', name: 'VJ Phoenix', image: '/images/vjs/default.jpg' },
  { id: 'vj-ronage', name: 'VJ Ronage', image: '/images/vjs/default.jpg' },
  { id: 'vj-ryan', name: 'VJ Ryan', image: '/images/vjs/default.jpg' },
  { id: 'vj-sammy', name: 'VJ Sammy', image: '/images/vjs/default.jpg' },
  { id: 'vj-shield', name: 'VJ Shield', image: '/images/vjs/default.jpg' },
  { id: 'vj-shoa-khah', name: 'VJ Shoa Khah', image: '/images/vjs/default.jpg' },
  { id: 'vj-son', name: 'VJ Son', image: '/images/vjs/default.jpg' },
  { id: 'vj-soul', name: 'VJ Soul', image: '/images/vjs/default.jpg' },
  { id: 'vj-tom', name: 'VJ Tom', image: '/images/vjs/default.jpg' },
  { id: 'vj-tonny', name: 'VJ Tonny', image: '/images/vjs/default.jpg' },
  { id: 'vj-ulio', name: 'VJ Ulio', image: '/images/vjs/default.jpg' },
  { id: 'vj-uncle-t', name: 'VJ Uncle T', image: '/images/vjs/default.jpg' },
  { id: 'vj-waza', name: 'VJ Waza', image: '/images/vjs/default.jpg' }
];

export const GENRE_DIRECTORY = [
  'Action',
  'Adventure',
  'Animation',
  'Biography',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Indian',
  'K-Drama',
  'Mystery',
  'Romance',
  'Sci-Fi',
  'Series',
  'Thriller',
  'VJ Movies',
  'War',
  'Western',
];

export const THEME = {
  colors: {
    background: '#0B0C10', // OLED Black
    primary: '#D90429',    // Crimson Strike
    text: '#FFFFFF',
    textMuted: '#888888',
    surface: '#1F2833'     // Deep tech grey for cards/menus
  }
};
